### ISSUE TITLE
Plugin support

### ISSUE THREAD

**Issue by fdion** [adamerose/PandasGUI#100]
As user base grows, features will be needed for domain specific applications. Some might clutter the interface, while other features might require many external dependencies. In order to not try to be jack of all trades and also reduce the support burden on pandasgui itself, a `plugin architecture` would provide a way for pandasgui functionality to be extended, for those users who want to develop plugins, or use some made by others.

For an example in a related application, see `Orange3` and [Orange3-timeseries](https://github.com/biolab/orange3-timeseries)

Given there is no pluggable pipeline (user defined DAG), plugin types would be needed for import / export (ie. specialized file type that needs to be converted to pandas, or preprocessing to convert on load), at the statistics level (ie, exotics/anomaly) and at the grapher level (new types of plots such as networks) or maybe even per tab (it is conceivable that someone would want to add to filters)

**Comment by adamerose** [comment]
Decided this is out of scope of PandasGUI. I don't think it would be feasible to allow users to add custom widgets, if they need something new in the UI they can submit a PR. And for potential plugins doing actions that just modify data and don't necessarily need to appear as a new widget in the UI, these can just be run directly in Python - my goal is for PandasGUI to work seamlessly alongside iPython
