### ISSUE TITLE
Group by mean on lines should not be applied by default

### ISSUE THREAD

**Issue by fdion** [adamerose/PandasGUI#103]
## Make group by on lines optional

Just tracked an issue where pretty much any time series with more than a handful of groupings just hangs pandasgui.

This is because group by explodes with each grouping, getting lots of zero values (or even null values if data has holes), creating a **sparse** dataframe in the billions of rows... The longer the time series or unique values in grouping, the worse it gets. ie. 30K values in X, col A with 14 values values and col B with 5 unique values, That's over **2B rows**, starting with a dataframe of only **30K** rows... Typical laptops start to really struggle at that point, and plotly just not displaying anything in many cases.

## Ask
- Maybe disable that until we have derived values? 
- or add a checkbox to enable this?
-  Or perhaps only include X and color. (Even then, if color is a continuous scale instead of a categorical, this could once more explode...)

Side benefit is that data is not masked when disabled.

**Comment by adamerose** [comment]
I've found in my own EDA that any line plot in Plotly without first doing a GroupBy usually gives me a worthless plot.
Here's an example:
```python
from pandasgui.datasets import pokemon
from pandasgui import show
import plotly.express as px

fig1 = px.line(data_frame=pokemon, y='Attack', x='Generation', color='Legendary')
fig2 = px.line(data_frame=pokemon.groupby(['Generation', 'Legendary']).mean().reset_index(),
               y='Attack', x='Generation', color='Legendary')
gui = show(fig1, fig2)
```
![image](https://user-images.githubusercontent.com/10884874/108743581-ea888080-7506-11eb-8ef1-55724a1a6abc.png)

Could you give an example where a line plot like the one on the left would be what the user really wants? In other tools like JMP this aggregation is also automatic, Seaborn too:
![image](https://user-images.githubusercontent.com/10884874/108744075-81553d00-7507-11eb-9099-dfd799cc8e2e.png)

**Comment by fdion** [comment]
Your x axis is categorical. That works because you are multiplying small numbers of unique row values, and aggregation on categoricals makes sense. For a continous X (any time dependent) or for X / Y of continous variables over time or ordinal grouping, you can't really groupby.

Seaborn does exclude continous variables, and will plot correctly if you can either group by hue (color), style (line_dash) and size (not on plotlyexpress lines, but can use ), or more simply, by specifying the column that identifies each line using units (and setting estimator=None). Plotly express does provide the same using line_grouping (which I added, but really needs to be used **instead** of aggregation). Difference is 30K point 300 lines taking over 1 hour to return on a beefy workstation, versus 300ms.

All of this to say that perhaps a minimum would be to disable the groupby if X is float, int or datetime (or more unique values than `constants.CATEGORICAL_THRESHOLD`)?

**Comment by adamerose** [comment]
> Your x axis is categorical. That works because you are multiplying small numbers of unique row values, and aggregation on categoricals makes sense. For a continous X (any time dependent) or for X / Y of continous variables over time or ordinal grouping, you can't really groupby.

Even with a continuous X, I only get a good plot using GroupBy.

```python
sns.lineplot(data=pokemon, y='Attack', x='Defense', hue='Legendary')
fig1 = px.line(data_frame=pokemon, y='Attack', x='Defense', color='Legendary')
fig2 = px.line(data_frame=pokemon.groupby(['Defense', 'Legendary']).mean().reset_index(),
               y='Attack', x='Defense', color='Legendary')
gui = show(fig1, fig2)
```
![image](https://user-images.githubusercontent.com/10884874/108755897-d304c400-7515-11eb-9867-febc3bf47c8b.png)

![image](https://user-images.githubusercontent.com/10884874/108756074-0cd5ca80-7516-11eb-85c6-e07f81f4a6b7.png)

I can't think of when it would make sense to have a line plot without aggregating all the Y values for a single X value, because if you don't do that you will have vertical line segments which I don't think is desirable.

**Comment by adamerose** [comment]
With `float` data on the X (and Y) the GroupBy is also needed to look correct and match Seaborn.

```python
from pandasgui.datasets import pokemon, stockdata, gapminder
from pandasgui import show
import plotly.express as px
import seaborn as sns
sns.lineplot(data=gapminder, y='lifeExp', x='gdpPercap', hue='continent')
fig1 = px.line(data_frame=gapminder, y='lifeExp', x='gdpPercap', color='continent')
fig2 = px.line(data_frame=gapminder.groupby(['gdpPercap', 'continent']).mean().reset_index(),
               y='lifeExp', x='gdpPercap', color='continent')
gui = show(fig1, fig2)
```
![image](https://user-images.githubusercontent.com/10884874/108757930-7eaf1380-7518-11eb-8222-5e1c0628811d.png)

**Comment by adamerose** [comment]
One more note - I just realized that in my `stockdata ` example above the graphs are broken because the date column was `string` not `datetime` so the x axis wasn't ordered properly after the GroupBy. I've updated `pandasgui.datasets` to read those columns as dates and the graphs look fine then, with or without GroupBy. 

I looked at Seaborn code and it seems like it always does aggregation for lineplots.

**Comment by fdion** [comment]
I think there is a misunderstanding... You are using non continuous X variables (except for the stock data which you found to be displaying incorrectly with group by). It doesn't really matter the underlying data type. Changing a categorical to an int, doesn't make it a continuous variable.In opening this ticket, I was referring to:
>pretty much any time series

Now, sometimes multiple time series are date time based, but many times they are not, they are just sequential. But each line is identified by some unique identifier. For example, digital audio sample number. power sweeps, diaphragm diameter from fully closed to fully open. Or they might be time based, but using a counter (experiment 1 of 200000, experiment 2 of 200000), epoch, unix timestamp, or some string. So the data type might be a datetime, a float, a string or an int. What they have in common is there are enough values that we no longer consider this a categorical variable, but a **continuous variable**. 

In that regard, "Time series like" data have to be handled differently. I can't share any of the users data or charts, but I'll try to make a demo example of timeseries where the group by takes forever. I'll get on this after I'm done with the automated title functionality.

**Comment by adamerose** [comment]
Okay I think I understand. It seems like you're talking about specifically making graphs where **there is a large number of X values and every single one is distinct** such as audio sample data where you have amplitude on Y and sample ID on X , in which case applying a GroupBy mean per sample ID is costly and results in the exact same thing as if you didn't do it at all.

I don't think whether variables might be considered "continuous" or "categorical" is that relevant. The same issue arises with categorical Y data like if instead of sampling amplitude you're sampling whether a sensor is on or off and wanted to plot that against sample ID.

Correct me if I'm still misunderstanding. But I with what I said above I can see now it would make sense to have a checkbox for whether or not to take the mean of Y within each X value (or more specifically, in each combined value of X + other keys like color). If the user specifies no aggregation but does have duplicate X values they will get a mess like the figures on the left in my examples above.

**Comment by fdion** [comment]
yep, you got it @adamerose ! It should be part of the EDA process to identify what does make the series unique. It gets compounded if you were looking at frequency spectrum, you would have number of samples x number of frequency bands. Add other group by (ie. samples at various gain) and it gets quickly out of hand: nb samples x bands x gains.

I think a checkbox that you can set to default one way or the other through settings would be super.

**Comment by fdion** [comment]
bar charts should also have the option of checkbox (not as much for performance, but to have better visibility into the data)

**Comment by adamerose** [comment]
Another note, regardless of whether or not we aggregate means I think it makes sense to always sort the data by the value on the X axis. I've just realized that lack of sorting is partially the reason my plots above without aggregation look all wonky (because GroupBy mean automatically sorts)

Example:

```
import plotly.express as px
from pandasgui import show

df = pd.DataFrame({'date': [pd.to_datetime("2020-01-01"),
                            pd.to_datetime("2020-01-02"),
                            pd.to_datetime("2020-01-03"),
                            pd.to_datetime("2020-01-04"),
                            pd.to_datetime("2020-01-05"),
                            pd.to_datetime("2020-01-06"),
                            pd.to_datetime("2020-01-07"),
                            pd.to_datetime("2020-01-08"),
                            pd.to_datetime("2020-01-09"),
                            pd.to_datetime("2020-01-10"),

                            ], 'val': [100, 200, 100, 500, 200, 900, 600, 800, 400, 800]})
df = df.sample(5, random_state=41)
fig1 = px.line(data_frame=df, x='date', y='val')
fig2 = px.line(data_frame=df.sort_values('date'), x='date', y='val')
show(fig1, fig2)

```

![image](https://user-images.githubusercontent.com/10884874/109069548-5ca3c580-76bf-11eb-833f-04e5a780834f.png)

**Comment by fdion** [comment]
> Another note, regardless of whether or not we aggregate means I think it makes sense to always sort the data by the value on the X axis. I've just realized that lack of sorting is partially the reason my plots above without aggregation look all wonky (because GroupBy mean automatically sorts)

I seem to remember that this might cause issue on long format data (there are none in your example datasets). On wide (tidy) data, that should always work. For visu.ai, I've set up where the users can sort up / down X, Y, Z or default to display by index number / file order. For auditing / data quality, it allows to see discontinuities (ie. data was added after the fact).

Are you working on the issue? I would know how to add a param to enable / disable, but not sure how/where I'd add a checkbox for bar / line only.

**Comment by fdion** [comment]
Further on this, sort works on long format data, but will need line_group to correctly plot to not get gaps. Perhaps sort should be part of schema for line and bar, like color etc, would make for a lot of flexibility.

**Comment by adamerose** [comment]
> Further on this, sort works on long format data, but will need line_group to correctly plot to not get gaps. Perhaps sort should be part of schema for line and bar, like color etc, would make for a lot of flexibility.

I'm not really sure what you mean by `line_group` being needed to plot data correctly, from my experience it seems like `line_group` is just equivalent to `color` just without the colors. I've never found it useful so I left it out of the main schema, and it can be added as a custom arg if the user wants. 

```
fig1 = px.line(data_frame=stockdata, y='value', x='Date', color='stock')
fig2 = px.line(data_frame=stockdata, y='value', x='Date', line_group='stock')
```
![image](https://user-images.githubusercontent.com/10884874/109188864-5f56f700-7761-11eb-9f8c-2e9a175053a0.png)

> I seem to remember that this might cause issue on long format data (there are none in your example datasets). On wide (tidy) data, that should always work. For visu.ai, I've set up where the users can sort up / down X, Y, Z or default to display by index number / file order. For auditing / data quality, it allows to see discontinuities (ie. data was added after the fact).

I don't think it ever makes sense to have the line crossing over itself, which is what can happen if you don't sort the data by the X variable like I discussed above. Gaps in data would happen not if things are out of order but if you have null Y value for a given X value, which I think is unrelated to this.



Tentatively I think I should implement this behavior for both line and bar plots:

- Always sort data by the column selected as the X variable so you don't get [graphs like this](https://github.com/adamerose/PandasGUI/issues/103#issuecomment-785404543).
- Add a checkbox (default True) for whether to aggregate the mean Y value within each value of X variable (+ group variables like color).  
- Note - With the checkbox checked, plots should always look correct, but if you are sure your data has no duplicate X values then unchecking it will improve performance and give the same graph.

> Are you working on the issue? I would know how to add a param to enable / disable, but not sure how/where I'd add a checkbox for bar / line only.

I can do this and have an idea for how it should be implemented already. In the Schemas defined for the Grapher the args are provided as `ColumnArg` instead of plain strings to allow the possibility for things like checkboxes and dropdown menus. So the UI shown for an arg will be defined by an if statement in `dragger.py` and in `grapher.py` you just need to put the corresponding Arg class in the Schema. I already have `OptionListArg` defined for a dropdown menu but never finished implementing this. I'll finish that and add a `BooleanArg` option for this

**Comment by fdion** [comment]
> > Further on this, sort works on long format data, but will need line_group to correctly plot to not get gaps. Perhaps sort should be part of schema for line and bar, like color etc, would make for a lot of flexibility.
> 
> I'm not really sure what you mean by `line_group` being needed to plot data correctly, from my experience it seems like `line_group` is just equivalent to `color` just without the colors. I've never found it useful so I left it out of the main schema, and it can be added as a custom arg if the user wants.

See `series_id` in below example. I did add `line_group` to schema already.

> I don't think it ever makes sense to have the line crossing over itself, which is what can happen if you don't sort the data by the X variable like I discussed above. Gaps in data would happen not if things are out of order but if you have null Y value for a given X value, which I think is unrelated to this.

Line can cross if you are tracking your X and Y as measures and your line is connected over time or similar. That's a really nice feature of connected scatter plots (_"The connected scatterplot can also be a powerfull technique to tell a story about the evolution of 2 variables"_ in below link). For example look at the Amanda vs Ashley (which is doable with line plot and hover for year, scatter has no dash line option)

https://www.data-to-viz.com/graph/connectedscatter.html

![connected](https://user-images.githubusercontent.com/1105325/109197696-50754200-776b-11eb-9956-b31641b4ead7.png)


On the gap, null Y is the cause, true, but in long format (different experiments over steps are pretty much all long format and require keeping the natural order as the data is found in the file) that's how data is stored. Assume one series of experiments record voltage over several 100 steps. Next series records reflected power over the same 100 steps. Just an example, but the point is that you will have one column for voltage with 100 values, followed by 100 nulls. the reflected power column will have the first 100 nulls, then 100 values. If you sort by X (step), then you will have value, null, value, null etc on one series and null, value, null, value etc on the second. You end up drawing segments, at best:

```
df = pd.DataFrame({
    
    'step': [1,2,3,4,5,6,7,8,9,10,
             1,2,3,4,5,6,7,8,9,10,],
    'series_id': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                  2, 2, 2, 2, 2, 2, 2, 2, 2, 2,],
   'val': [100, 200, 100, 500, 200, 900, 600, 800, 400, 800, 
           None, None,None,None,None,None,None,None,None,None,],
   'val2': [None, None,None,None,None,None,None,None,None,None,
            200, 300, 200, 600, 300, 1000, 700, 900, 500, 900]})

# Note, data is in order of experiments (recording val first, then recording val2
fig1 = px.line(data_frame=df, x='step', y=['val','val2'])
fig2 = px.line(data_frame=df.sort_values('step'), x='step', y=['val','val2'])
```

fig1 (natural order from the data file, which is `series_id`, `step`):
![natural_order](https://user-images.githubusercontent.com/1105325/109197144-a7c6e280-776a-11eb-93c3-595c3da180c5.png)

fig2 (sorted by x):
![sorted_by_x](https://user-images.githubusercontent.com/1105325/109197245-c3ca8400-776a-11eb-9846-9c32fd94f262.png)

To fix 2, you have to use `line_group='series_id'`
> Tentatively I think I should implement this behavior for both line and bar plots:
>     * Always sort data by the column selected as the X variable so you don't get [graphs like this](https://github.com/adamerose/PandasGUI/issues/103#issuecomment-785404543).

if this can be similarly parametrized from settings and or enabled/disabled. I've been collecting usage data, and so far about 3 out of 4 line plots are of the above illustrated structure. I think forcing sort would be a big issue for these users.

Also, if you look at the bar chart I put in the PR for automated titles:

![bar_chart](https://user-images.githubusercontent.com/1105325/109198859-b7dfc180-776c-11eb-8397-41ff765caa87.png)

The natural order very conveniently displays the progression of number of cylinders over observations as you go up the bar. if sort column was part of the schema, then you could also sort by any other criteria, including number of cylinders, providing different views and insight into the data.

**Comment by adamerose** [comment]
Done! I still want to add hover tooltips and add dropdown menus for things like aggregation type, but I think what we discussed is done so try it and let me know if there's any issue.

![image](https://user-images.githubusercontent.com/10884874/109268805-9a950c80-77d9-11eb-8abe-cb5f6179f579.png)

BTW I ran into another edge case, where even sorting the data resulted in a broken graph. I had to resort to modifying the figure's x-axis to be categorical. In the Grapher logic I do this for line/bar plots if the x-axis is `object` dtype.

Example
```
from pandasgui.datasets import pokemon
from pandasgui import show
import plotly.express as px

pokemon = pokemon.query('Generation in [1,2]')
df = pokemon.groupby(['Generation', 'Type 1']).mean().reset_index().sort_values(['Type 1', 'Generation'])

fig1 = px.line(data_frame=df, x='Type 1', y='Total', color='Generation', hover_name='#')
fig2 = px.line(data_frame=df, x='Type 1', y='Total', color='Generation', hover_name='#')
fig2.update_xaxes(type='category', categoryorder='category ascending')

gui = show(fig1, fig2)
```
![image](https://user-images.githubusercontent.com/10884874/109268935-c9ab7e00-77d9-11eb-84f0-5b22653cff74.png)

**Comment by fdion** [comment]
Took a quick look at the code and noticed:

https://github.com/adamerose/PandasGUI/blob/bf6d187c738b0509783e404f9932659a6d261acd/pandasgui/widgets/grapher.py#L223

should say line (code history comment) and not bar

I'll be testing next.

**Comment by fdion** [comment]
This makes a big difference, having groupby disabled, especially those that were using enough memory that pages were constantly swapping in and out. 6 to 10 seconds.

Two suggestions for UX:
- Would it be possible to add some space between `facet_col` and `apply_mean` so it is clear apply_mean and apply_sort are tied to facet_col
- would it be possible to either pass this through settings like I did for render_mode (and default to checked if not provided so it doesn't affect your use cases) or set it through the GUI settings and persist choice? If you drag and drop 30 files that all need to be unchecked, you have to remember to uncheck this in each dataframe. With the type of data some of my users have, if they forget, they get a spinner for the next hour...

I'll also create an issue to update the automated title to reflect the checkboxes and I'll work on it

**Comment by adamerose** [comment]
> * Would it be possible to add some space between `facet_col` and `apply_mean` so it is clear apply_mean and apply_sort are not tied to facet_col

An alternative to adjusting vertical spacing would be override the styling to put the checkbox on the right instead of left, so the text doesn't look like it's indented under the previous item.

> would it be possible to either pass this through settings like I did for render_mode (and default to checked if not provided so it doesn't affect your use cases) or set it through the GUI settings and persist choice? If you drag and drop 30 files that all need to be unchecked, you have to remember to uncheck this in each dataframe. With the type of data some of my users have, if they forget, they get a spinner for the next hour...

Yeah that's doable, probably just need to make the `default_value` in the schema defined under grapher.py read from the store settings like with other cached settings. 


Don't have time today for those two changes but agree they would be good. So you can do them or wait until I get to it

**Comment by fdion** [comment]
The challenge is that schemas is assigned when module is imported and it gets assigned the default value before settings are even initialized and assigned to store... thoughts?

**Comment by adamerose** [comment]
Hmm that's a good point. I wonder if it would make sense to make `Settings` a global object that gets initialized on import and shared across all PandasGUI. Then it could be importing

**Comment by fdion** [comment]
Might be the way to go. Also, I think that quite a bit more settings would be beneficial to pass through. Just off the top of my head, I'm thinking stuff like width and height of plot, default tab to start on, default hart type selection, default theme for plot (_different from the theme of the UI - dark mode might work for UI, but for printing etc..._), so the **easier it is to add to it, the better**.

**Comment by fdion** [comment]
Ended up import schemas in gui and modifying the list based on chart name and arg_name:

https://github.com/adamerose/PandasGUI/pull/108

**Comment by fdion** [comment]
also, when are you doing the next pypi release? I have several users I'll need to get updated to this version.

**Comment by adamerose** [comment]
I'll probably do a release this weekend after I implement the persistent Grapher settings discussed above.

**Comment by adamerose** [comment]
Made settings global and added a widget and menu option to open it for adjusting settings. Also did a PyPi release 0.2.10

**Comment by adamerose** [comment]
Added a settings editor and released 0.2.10 to PyPi. There's still the problem where since Grapher settings are set on import that modifying the SettingsStore doesn't take effect, but at least now you can set a default and it will take effect after you reopen PandasGUI and every time after.

**Comment by fdion** [comment]
great, thanks! Will make things easier for the users.

Just one note, you left a print statement in the settings editor:
https://github.com/adamerose/PandasGUI/blob/b0154fe972e57c9a17d679f4a57756f9a9c2ae97/pandasgui/widgets/settings_editor.py#L24

**Comment by adamerose** [comment]
Removed the print with 0.2.10.1 pypi release. I'll close this thread now, improving settings behavior further can be another issue but I'll leave that for someone else to make when it comes up since it's low priority for me

**Comment by adamerose** [comment]
> fig2 (sorted by x):
> To fix 2, you have to use `line_group='series_id'`

I found a better fix

```
import pandas as pd
import plotly.express as px
from pandasgui import show

df = pd.DataFrame({

    'step': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ],
    'series_id': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                  2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ],
    'val': [100, 200, 100, 500, 200, 900, 600, 800, 400, 800,
            None, None, None, None, None, None, None, None, None, None, ],
    'val2': [None, None, None, None, None, None, None, None, None, None,
             200, 300, 200, 600, 300, 1000, 700, 900, 500, 900]})

# Note, data is in order of experiments (recording val first, then recording val2
fig1 = px.line(data_frame=df, x='step', y=['val', 'val2'])
fig2 = px.line(data_frame=df.sort_values('step'), x='step', y=['val', 'val2'])
fig2.update_traces(connectgaps=True)
show(fig2)
```


![image](https://user-images.githubusercontent.com/10884874/112712934-dbe80d00-8ea8-11eb-94e3-4c25f4f3d7ae.png)
