### ISSUE TITLE
Grapher: fonts are really tiny

### ISSUE THREAD

**Issue by miglto** [adamerose/PandasGUI#113]
Running Ubuntu on a retina macbook pro - just this OS on the laptop, not virtualized. Fonts in Grapher are very tiny, unreadable.

**Comment by fdion** [comment]
If you add a custom kwargs of:
`template` = `presentation`

Does that help? either way you should attach a screenshot.

**Comment by miglto** [comment]
Here's a screenshot... 
Adding template=presentation does help! Thank you.
Is there a way to specify a global font size for plotly?
![Screenshot from 2021-03-02 21-39-21](https://user-images.githubusercontent.com/51788468/109744320-127b8200-7ba0-11eb-9abd-d336f2cdf8e2.png)

**Comment by fdion** [comment]
At 27" it wouldn't be too bad, but on a laptop :(

can you attach your display settings? Depending on your window manager, you can set a scale for menus and title bars. if this is set to anything but 1, you will have a mismatch between what is rendered in plotly and the user interface / window manager.

If you are using the scale option, I would reset to 1 and change DPI instead.

**Comment by fdion** [comment]
Also, ATM, there is no way to set a global font size. I just added textfont_size for text labels on line / bar plots in a current PR, but that doesn't address title, legend, axis, annotations etc. 

Basically, the only way to do it right now is through template. `presentation` makes everything **large** (_if not, we need to find out what is wrong with your config_) and would be the correct way to do it. Plus you can specify `template` = some theme + presentation (ie. `seaborn+presentation`, `plotly+presentation`)

**Comment by adamerose** [comment]
Please check if you have the same problem when directly creating a graph with Plotly Express and viewing it in a browser or Jupyter, to rule out any specific interactions with PandasGUI

**Comment by miglto** [comment]
Here are my display settings - two displays, my macbook pro 13 retina and a 28" Acer (my macbook only has Ubuntu installed, not running as a VM):
![Screenshot from 2021-03-03 10-27-16](https://user-images.githubusercontent.com/51788468/109830580-a1be7f00-7c0c-11eb-9cd7-8f97e43b608f.png)
![Screenshot from 2021-03-03 10-27-32](https://user-images.githubusercontent.com/51788468/109830601-a5ea9c80-7c0c-11eb-951c-b92052d8c360.png)

And here is what I see in pandasgui on the 28" (which is a 4k monitor (same on the 13"):
![Screenshot from 2021-03-03 10-32-18](https://user-images.githubusercontent.com/51788468/109830795-d29eb400-7c0c-11eb-93d8-68ccce0ab376.png)

And here is a plot in Dash which shows reasonable fonts:
![Screenshot from 2021-03-03 10-35-08](https://user-images.githubusercontent.com/51788468/109830923-f2ce7300-7c0c-11eb-9c67-77f3b07c371b.png)

**Comment by miglto** [comment]
> Also, ATM, there is no way to set a global font size. I just added textfont_size for text labels on line / bar plots in a current PR, but that doesn't address title, legend, axis, annotations etc.
> 
> Basically, the only way to do it right now is through template. `presentation` makes everything **large** (_if not, we need to find out what is wrong with your config_) and would be the correct way to do it. Plus you can specify `template` = some theme + presentation (ie. `seaborn+presentation`, `plotly+presentation`)

Is it possible to pass a template argument to pdg.show()?

**Comment by miglto** [comment]
> At 27" it wouldn't be too bad, but on a laptop :(
> 
> can you attach your display settings? Depending on your window manager, you can set a scale for menus and title bars. if this is set to anything but 1, you will have a mismatch between what is rendered in plotly and the user interface / window manager.
> 
> If you are using the scale option, I would reset to 1 and change DPI instead.

Just tried this - changed my laptop display to 100% (rather than 125%) - and this fixed the problem. Even on my 28" display which was already set at 100%. Go figure. Dash did not have an issue here though.

**Comment by adamerose** [comment]
Interesting that Dash doesn't have the problem... might be specific to Plotly Express? Try this snippet and let me know which of the 3 methods has the problem.
```
from pandasgui import show
from pandasgui.datasets import pokemon
from pandasgui.widgets.plotly_viewer import PlotlyViewer
import plotly.express as px

# This should appear in web browser
fig1 = px.scatter(data_frame=pokemon, x='Attack', y='Defense')
fig1.show(renderer='browser')

# This should appear in standalone PyQt window
fig2 = px.scatter(data_frame=pokemon, x='Attack', y='Defense')
pv = PlotlyViewer(fig2)
pv.show()

# This should appear in PandasGUI in the Grapher tab
fig3 = px.scatter(data_frame=pokemon, x='Attack', y='Defense')
gui = show(pokemon)
gui.store.selected_pgdf.dataframe_explorer.grapher.figure_viewer.set_figure(fig3)
```

**Comment by miglto** [comment]
I am getting the error:

QWidget: Must construct a QApplication before a QWidget
Aborted (core dumped)

**Comment by adamerose** [comment]
> The middle case using PlotlyViewer gives me an error:

Try this snippet. Also go and open the `.html` file in your browser, the one at the path printed by this snippet.

```
from PyQt5 import QtWidgets
from pandasgui.datasets import pokemon
from pandasgui.widgets.plotly_viewer import PlotlyViewer
import plotly.express as px

fig = px.scatter(data_frame=pokemon, x='Attack', y='Defense')
app = QtWidgets.QApplication([])
pv = PlotlyViewer(fig)
pv.show()

print(pv.temp_file.name)

app.exec_()

```

**Comment by miglto** [comment]
In this case the PlotlyViewer window has tiny font whereas the html does not:
![Screenshot from 2021-03-03 15-15-11](https://user-images.githubusercontent.com/51788468/109866563-6b482a80-7c33-11eb-9948-e11d33923b36.png)

**Comment by adamerose** [comment]
It looks like it's not specifically the font but the overall scaling/zoom because the graph points are also smaller. The Plotly Viewer window does support zooming in with Ctrl+MouseWheelUp which I think would probably fix your problem but a hassle to zoom in every time you plot something. Not sure why the default zoom level is wrong for you, thought some of my custom CSS overrides might be the culprit but since the same HTML file looks fine in browser it seems like a unique interaction between your OS, resolution settings and `PyQt5.QtWebEngineWidgets.QWebEngineView`. I use 125% scaling on Windows 10 and don't have this. I doubt I can fix it by changing my code, and you're probably the only person that will ever run PandasGUI on a Macbook retina display running Ubuntu haha, so closing this. Can reopen if anyone else has the same issue or figures out a fix.

**Comment by miglto** [comment]
Just FYI, to get bac to the original resolution I like on the macbook monitor, I added a custom resolution in Ubuntu (so I don't have to use 125% scaling) and it works great and clears the pandasgui scaling issue.

All necessary info is here in case someone else needs to do this:

https://ubuntuhandbook.org/index.php/2017/04/custom-screen-resolution-ubuntu-desktop/
