### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by cristeam29** [adamerose/PandasGUI#115]
Hi! I tried to install the package on PyCharm. I am running python 3.9, windows 10. I get this error. Any ideas how to sort this out? Thanks!

ERROR: Command errored out with exit status 1:
     command: 'c:\users\cris\pycharmprojects\getdailyvolume\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Cris\\AppData\\Local\\Temp\\pip
-install-srzg188j\\wordcloud_e5af7f5a75624ef6b5a84fcca69a80a6\\setup.py'"'"'; __file__='"'"'C:\\Users\\Cris\\AppData\\Local\\Temp\\pip-install-srzg188j\\wordcloud_e5af7f5a75624ef6b5a84fcc
a69a80a6\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' in
stall --record 'C:\Users\Cris\AppData\Local\Temp\pip-record-l5_tv5_z\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\cris\pycharmprojects\get
dailyvolume\venv\include\site\python3.9\wordcloud'
         cwd: C:\Users\Cris\AppData\Local\Temp\pip-install-srzg188j\wordcloud_e5af7f5a75624ef6b5a84fcca69a80a6\
    Complete output (26 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\color_from_image.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\tokenization.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\wordcloud.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\wordcloud_cli.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\_version.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\__init__.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\__main__.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\stopwords -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-3.9\wordcloud
    UPDATING build\lib.win-amd64-3.9\wordcloud/_version.py
    set build\lib.win-amd64-3.9\wordcloud/_version.py to '1.8.1'
    running build_ext
    building 'wordcloud.query_integral_image' extension
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\wordcloud
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\cris\pycharmprojects\get
dailyvolume\venv\include -IC:\Users\Cris\AppData\Local\Programs\Python\Python39\include -IC:\Users\Cris\AppData\Local\Programs\Python\Python39\include -IC:\Program Files (x86)\Microsoft V
isual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include /Tcwordcloud/query_integral_image.c /Fobuild\temp.win-amd64-3.9\Release\wordcloud/query_integral_image.obj
    query_integral_image.c
    C:\Users\Cris\AppData\Local\Programs\Python\Python39\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\cris\pycharmprojects\getdailyvolume\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users
\\Cris\\AppData\\Local\\Temp\\pip-install-srzg188j\\wordcloud_e5af7f5a75624ef6b5a84fcca69a80a6\\setup.py'"'"'; __file__='"'"'C:\\Users\\Cris\\AppData\\Local\\Temp\\pip-install-srzg188j\\w
ordcloud_e5af7f5a75624ef6b5a84fcca69a80a6\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(cod
e, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Cris\AppData\Local\Temp\pip-record-l5_tv5_z\install-record.txt' --single-version-externally-managed --compile --install-headers '
c:\users\cris\pycharmprojects\getdailyvolume\venv\include\site\python3.9\wordcloud' Check the logs for full command output.

**Comment by adamerose** [comment]
Looks like it's failing to install the `wordcloud` dependency

https://github.com/TomasKeller/python-WordCloud

You could try installing the .whl, this is an excerpt from their docs

> Installation notes
> worcloud depends on numpy>=1.5.1, pillow and matplotlib. To install it via pip, you will also need a C compiler.
> 
> Windows
> If you're having trouble with pip installation on windows, you can find a .whl file at:
> 
> http://www.lfd.uci.edu/~gohlke/pythonlibs/#wordcloud

**Comment by cristeam29** [comment]
Many thanks! I installed wordcloud separately and it worked.
