### ISSUE TITLE
Candle stick graph type

### ISSUE THREAD

**Issue by riodda** [adamerose/PandasGUI#117]
Would be cool to have candlestick graph type, pltotly has good support of them.

**Comment by adamerose** [comment]
![image](https://user-images.githubusercontent.com/10884874/118097260-74c2e100-b3a0-11eb-8aec-ff0dc717957a.png)

```python
from pandasgui import show
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv')
show(df)
```
