### ISSUE TITLE
No response when using block=False

### ISSUE THREAD

**Issue by hkdavechan** [adamerose/pandasgui#12]
tested your example of 
    flights = sns.load_dataset('flights')
    multi = flights.set_index(['year', 'month']).unstack()  # MultiIndex example
    show(flights, flightsReshaped=multi, block=False)

the GUI pops up but blank out with "NoResponse"

![image](https://user-images.githubusercontent.com/33200708/68547365-b4abaf80-041b-11ea-8f9d-11b13eaca7cf.png)

**Comment by adamerose** [comment]
I wasn't able to reproduce this, and may have fixed it with my other improvements since this was made. Please reply again if you still have this issue on the latest release and I'll look into it, and let me know your OS.
