### ISSUE TITLE
Generate or log python code to (re) do the analysis

### ISSUE THREAD

**Issue by vnijs** [adamerose/PandasGUI#124]
This is great tool! Would it also be possible to generate/log/return python code that could be used to redo the analysis (i.e., make the work reproducible)? I did this in Radiant for R (video below) and think it could be a really valuable addition to PandasGui

https://www.youtube.com/watch?v=pNNQc2lHR8Q

**Comment by adamerose** [comment]
This is already possible, see https://github.com/adamerose/PandasGUI/issues/59

It's under Edit -> Code Export

![image](https://user-images.githubusercontent.com/10884874/112534644-af85a100-8d81-11eb-9c03-0b0bd463b595.png)
