### ISSUE TITLE
Looking for sample datasets

### ISSUE THREAD

**Issue by adamerose** [adamerose/PandasGUI#128]
I'm looking for new datasets to add to `pandasgui.datasets`, let me know if you have any suggestions!

Ideally datasets that...

- cover a novel or interesting topic and that doesn't require extensive domain knowledge
- have decent number of rows and columns that cover a variety of datatypes
- can be used to effectively demonstrate a variety of different charts and analyses

**Comment by bjornjorgensen** [comment]
https://github.com/ZaxR/pandas_multiindex_tutorial he also have this https://youtu.be/kP-0ET0V5Tc where he are using the datas.

**Comment by bjornjorgensen** [comment]
pycaret have many datasets https://github.com/pycaret/pycaret
