### ISSUE TITLE
resizing index names on multiindixing dataframes

### ISSUE THREAD

**Issue by bjornjorgensen** [adamerose/PandasGUI#129]
Hi, I have this huge dataframe 

['DOFFIN_ESENDERS.DOFFIN_APPENDIX',
 'DOFFIN_ESENDERS.DOFFIN_APPENDIX.EXPRESSION_OF_INTEREST_URL',
 'DOFFIN_ESENDERS.DOFFIN_APPENDIX.PUBLISH_TO_TED',
 'DOFFIN_ESENDERS.DOFFIN_APPENDIX.REFERENCE_SECTION.REFERENCE_DOFFIN',
 'DOFFIN_ESENDERS.DOFFIN_APPENDIX.URL_DOCUMENT',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CATEGORY',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_MEDIATION_BODY.ADDRESS',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_MEDIATION_BODY.COUNTRY.VALUE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_MEDIATION_BODY.E_MAIL',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_MEDIATION_BODY.FAX',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_MEDIATION_BODY.OFFICIALNAME',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_MEDIATION_BODY.PHONE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_MEDIATION_BODY.POSTAL_CODE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_MEDIATION_BODY.TOWN',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_MEDIATION_BODY.URL',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_REVIEW_BODY.ADDRESS',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_REVIEW_BODY.COUNTRY.VALUE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_REVIEW_BODY.E_MAIL',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_REVIEW_BODY.FAX',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_REVIEW_BODY.OFFICIALNAME',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_REVIEW_BODY.PHONE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_REVIEW_BODY.POSTAL_CODE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_REVIEW_BODY.TOWN',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_REVIEW_BODY.URL',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_REVIEW_INFO.ADDRESS',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_REVIEW_INFO.COUNTRY.VALUE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_REVIEW_INFO.E_MAIL',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_REVIEW_INFO.FAX',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_REVIEW_INFO.OFFICIALNAME',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_REVIEW_INFO.PHONE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_REVIEW_INFO.POSTAL_CODE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_REVIEW_INFO.TOWN',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.ADDRESS_REVIEW_INFO.URL',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.DATE_DISPATCH_NOTICE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.EINVOICING',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.EORDERING',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.EPAYMENT',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.INFO_ADD.P',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.COMPLEMENTARY_INFO.REVIEW_PROCEDURE.P',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY.ADDRESS',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY.CONTACT_POINT',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY.COUNTRY.VALUE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY.E_MAIL',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY.FAX',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY.LOCATION.code',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY.NATIONALID',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY.NUTS.CODE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY.PHONE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY.POSTAL_CODE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY.TOWN',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY.URL_BUYER',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY.URL_GENERAL',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY_ADDITIONAL.ADDRESS',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY_ADDITIONAL.CONTACT_POINT',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY_ADDITIONAL.COUNTRY.VALUE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY_ADDITIONAL.E_MAIL',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY_ADDITIONAL.LOCATION.code',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY_ADDITIONAL.NATIONALID',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY_ADDITIONAL.NUTS.CODE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY_ADDITIONAL.OFFICIALNAME',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY_ADDITIONAL.PHONE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY_ADDITIONAL.POSTAL_CODE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY_ADDITIONAL.TOWN',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY_ADDITIONAL.URL_GENERAL',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_FURTHER_INFO.ADDRESS',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_FURTHER_INFO.CONTACT_POINT',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_FURTHER_INFO.COUNTRY.VALUE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_FURTHER_INFO.E_MAIL',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_FURTHER_INFO.LOCATION.code',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_FURTHER_INFO.NATIONALID',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_FURTHER_INFO.OFFICIALNAME',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_FURTHER_INFO.PHONE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_FURTHER_INFO.POSTAL_CODE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_FURTHER_INFO.TOWN',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_FURTHER_INFO.URL_BUYER',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_FURTHER_INFO.URL_GENERAL',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_FURTHER_INFO_IDEM',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_PARTICIPATION.ADDRESS',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_PARTICIPATION.CONTACT_POINT',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_PARTICIPATION.COUNTRY.VALUE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_PARTICIPATION.E_MAIL',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_PARTICIPATION.LOCATION.code',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_PARTICIPATION.NATIONALID',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_PARTICIPATION.OFFICIALNAME',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_PARTICIPATION.PHONE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_PARTICIPATION.POSTAL_CODE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_PARTICIPATION.TOWN',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_PARTICIPATION.URL_GENERAL',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_PARTICIPATION_IDEM',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.CA_ACTIVITY.VALUE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.CA_ACTIVITY_OTHER',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.CA_TYPE.VALUE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.CA_TYPE_OTHER',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.CENTRAL_PURCHASING',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.DOCUMENT_FULL',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.DOCUMENT_RESTRICTED',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.JOINT_PROCUREMENT_INVOLVED',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.PROCUREMENT_LAW.P',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.URL_DOCUMENT',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.URL_PARTICIPATION',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.URL_TOOL',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.FORM',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.LEFTI',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.LEFTI.ECONOMIC_CRITERIA_DOC',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.LEFTI.ECONOMIC_FINANCIAL_INFO.P',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.LEFTI.ECONOMIC_FINANCIAL_MIN_LEVEL.P',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.LEFTI.PARTICULAR_PROFESSION.CTYPE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.LEFTI.PERFORMANCE_CONDITIONS.P',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.LEFTI.PERFORMANCE_STAFF_QUALIFICATION',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.LEFTI.REFERENCE_TO_LAW.P',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.LEFTI.RESTRICTED_SHELTERED_WORKSHOP',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.LEFTI.SUITABILITY.P',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.LEFTI.TECHNICAL_CRITERIA_DOC',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.LEFTI.TECHNICAL_PROFESSIONAL_INFO.P',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.LEFTI.TECHNICAL_PROFESSIONAL_MIN_LEVEL.P',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.LEGAL_BASIS.VALUE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.LG',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.CPV_MAIN.CPV_CODE.CODE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.DATE_PUBLICATION_NOTICE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.ITEM',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.LOT_DIVISION',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.LOT_DIVISION.LOT_ALL',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.LOT_DIVISION.LOT_COMBINING_CONTRACT_RIGHT.P',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.LOT_DIVISION.LOT_MAX_ONE_TENDERER',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.LOT_DIVISION.LOT_ONE_ONLY',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.NO_LOT_DIVISION',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.AC.AC_PRICE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.AC.AC_PRICE.AC_WEIGHTING',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.AC.AC_PROCUREMENT_DOC',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.AC.AC_QUALITY',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.ACCEPTED_VARIANTS',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.AC_COST.AC_CRITERION',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.AC_COST.AC_WEIGHTING',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.AC_PRICE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.AC_PRICE.AC_WEIGHTING',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.AC_PROCUREMENT_DOC',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.AC_QUALITY',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.AC_QUALITY.AC_CRITERION',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.AC_QUALITY.AC_WEIGHTING',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.CPV_ADDITIONAL.CPV_CODE.CODE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.DATE_END',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.DATE_START',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.DURATION.TYPE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.DURATION.text',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.INFO_ADD.P',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.ITEM',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.LOCATION.code',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.LOT_NO',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.MAIN_SITE.P',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.NO_EU_PROGR_RELATED',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.NUTS.CODE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.OPTIONS',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.OPTIONS_DESCR.P',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.RENEWAL',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.RENEWAL_DESCR.P',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.SHORT_DESCR.P',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.TITLE.P',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.VAL_OBJECT.CURRENCY',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.OBJECT_DESCR.VAL_OBJECT.text',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.REFERENCE_NUMBER',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.SHORT_DESCR.P',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.TITLE.P',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.TYPE_CONTRACT.CTYPE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.VAL_ESTIMATED_TOTAL.CURRENCY',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT.VAL_ESTIMATED_TOTAL.text',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.PROCEDURE.CONTRACT_COVERED_GPA',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.PROCEDURE.DATE_AWARD_SCHEDULED',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.PROCEDURE.DATE_RECEIPT_TENDERS',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.PROCEDURE.EAUCTION_USED',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.PROCEDURE.FRAMEWORK.NB_PARTICIPANTS',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.PROCEDURE.FRAMEWORK.SEVERAL_OPERATORS',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.PROCEDURE.FRAMEWORK.SINGLE_OPERATOR',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.PROCEDURE.INFO_ADD_EAUCTION.P',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.PROCEDURE.LANGUAGES.LANGUAGE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.PROCEDURE.LANGUAGES.LANGUAGE.VALUE',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.PROCEDURE.NO_CONTRACT_COVERED_GPA',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.PROCEDURE.PT_COMPETITIVE_NEGOTIATION',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.PROCEDURE.PT_RESTRICTED',
 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.PROCEDURE.TIME_RECEIPT_TENDERS',
 'DOFFIN_ESENDERS.FORM_SECTION.NOTICE_UUID',
 'DOFFIN_ESENDERS.http://www.w3.org/2001/XMLSchema-instance:noNamespaceSchemaLocation',
 'DOFFIN_ESENDERS.xmlns.xsi']

and when I make an multiindex like this

df2 = df.set_index(['DOFFIN_ESENDERS.FORM_SECTION.F01_2014.OBJECT_CONTRACT', 'DOFFIN_ESENDERS.DOFFIN_APPENDIX', 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_CONTRACTING_BODY_ADDITIONAL.OFFICIALNAME', 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.CONTRACTING_BODY.ADDRESS_PARTICIPATION.OFFICIALNAME', 'DOFFIN_ESENDERS.FORM_SECTION.F01_2014.FORM'], inplace=True)

Then I cant resize the labels on the columns that are in the multiindex.  

I can give you acess to my arangodb server it you well try it with some data.

**Comment by adamerose** [comment]
This isn't a bug or specific to your data, resizing the columns of the index is just not supported yet.  I'll leave this open as a feature request

Currently you can only resize:  
- The height of the rows of the vertical header (the one at the left of the table)
- The width of the columns of the horizontal header (the one at the top of the table)


Until then, a workaround is to `.reset_index()` your DataFrame before viewing it

**Comment by adamerose** [comment]
This is possible now (install from Github or wait for 0.2.13)
