### ISSUE TITLE
Can this be integrated with Django?

### ISSUE THREAD

**Issue by robertomano24** [adamerose/pandasgui#13]

**Comment by adamerose** [comment]
Do you mean like displaying this GUI inside a web page built on Django? 

I have no experience with Django so I probably won't do this, but if anyone wants to take a stab at it I'll accept a PR as long as its modular and not cluttering the core code. This seems like a good starting point: https://wiki.python.org/moin/PyQt/Embedding%20Widgets%20in%20Web%20Pages
