### ISSUE TITLE
Statistics view doesn't refresh

### ISSUE THREAD

**Issue by adamerose** [adamerose/PandasGUI#133]
Statistics view doesn't refresh even when enabled in settings

_Originally posted by @bjtulinl in Discussions

**Comment by bjtulinl** [comment]
Hi, i think there is a better way to refresh the statistics. The statistics in stats_viewer connects to stats_viewer.dataframe_viewer.pgdf.df.
Update df with the new statistics and use stats_viewer.dataframe_viewer.refresh_ui can do it. 
Hope it will help :)

**Comment by adamerose** [comment]
@bjtulinl I don't think I understand what your suggested change is, maybe you could clarify or submit a pull request? `DataFrameViewer` (dataframe_viewer.py) is purely for displaying a DataFrame as a table. `dataframe_viewer.refresh_ui` is for refreshing the `DataFrameViewer` widget UI to reflect any changes to the underlying DataFrame it is displaying. The current flow of refreshing statistics is like this:

1. A DataFrame is imported to PandasGUI
2. It is wrapped inside a PandasGuiDataFrameStore (and throughout my code I refer to instances of these as `pgdf`s)
3. The main DataFrame is stored at `pgdf.df_unfiltered` and the DataFrame with filters applied is stored at `pgdf.df`
4. The `refresh_statistics` of the PandasGuiDataFrameStore calculates summary statistics of `pgdf.df` and stores them under `pgdf.column_statistics` (as another DataFrame object), this is what gets display inside the `StatisticsViewer`
5. This refresh_statistics` method gets called to calculate these statistics on __init__ as well as any time the `data_changed` method runs which happens if any data inside the primary DataFrame gets modified. This `data_changed` method also triggers `refresh_ui`

**Comment by bjtulinl** [comment]
I mean when the statistics are changed you only update them in the main pgdf. But you have another pgdf in stats_viewer.dataframe_viewer. The displayed statistics are from stats_viewer.dataframe_viewer.pgdf.df. You have to update the new statistics into this DataFrame and refresh ui. Is it clear? ;) Sorry for my poor expaination.

**Comment by adamerose** [comment]
I think you may just be still using the version without my fix, right now when I toggle a filter it updates both the main DataFrame as well as the stats DataFrame shown in the Statistics tab. This just isn't released yet, to get the fix you have to install the unreleased changes like shown in the README or wait for my next release probably this week.

Or maybe I'm still misunderstanding what you mean.. Here's how it looks for me when I toggle the filter on and off with the latest fixes

![image](https://user-images.githubusercontent.com/10884874/118297076-b12f3380-b4ab-11eb-86f4-cd01259b4412.png)

![image](https://user-images.githubusercontent.com/10884874/118297192-d3c14c80-b4ab-11eb-964e-d0c4c233f93c.png)

**Comment by bjtulinl** [comment]
I know. But maybe it's better to update the source data of statistics and reset the model instead of pasting the new statistics.
