### ISSUE TITLE
"Plotly Express canont process wide-form data with columns of different type"

### ISSUE THREAD

**Issue by Adlopez2016** [adamerose/PandasGUI#136]
Hello we are trying to integrate pandasgui to a project in Django, however it generates the following error "Plotly Express canont process wide-form data with columns of different type". Please could you help me

![photo4976905474817501523](https://user-images.githubusercontent.com/21997143/118419637-3704d780-b682-11eb-8b7a-8b8618fc2551.jpg)

**Comment by adamerose** [comment]
This is the error message Plotly often gives you when you provide it no arguments. Not a specific problem with PandasGUI. The PandasGUI Grapher tries running code equivalent to the snippet below when you don't give it any columns.

```
import plotly.express as px
from pandasgui.datasets import pokemon as df
fig = px.bar(data_frame=df, x=None, y=None, color=None, facet_row=None, facet_col=None, )
```
```
ValueError: Plotly Express cannot process wide-form data with columns of different type.
```
