### ISSUE TITLE
TypeError: 'exclusive' is an unknown keyword argument

### ISSUE THREAD

**Issue by malapradej** [adamerose/pandasgui#14]
I have installed the latest version today. I get the following error when running `show(lib_1_3_df)` with a pandas DataFrame:
                                                                                                         
	Using existing QApplication instance
	Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
	Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
	Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
	---------------------------------------------------------------------------
	TypeError                                 Traceback (most recent call last)
	<ipython-input-7-b463f0b55e1e> in <module>
	----> 1 show(lib_1_3_df)

	~/anaconda3/lib/python3.7/site-packages/pandasgui/gui.py in show(block, *args, **kwargs)
	    362     kwargs = {**kwargs, **dataframes}
	    363 
	--> 364     pandas_gui = PandasGUI(**kwargs)
	    365 
	    366     if block:

	~/anaconda3/lib/python3.7/site-packages/pandasgui/gui.py in __init__(self, **kwargs)
	     74 
	     75         # Generates all UI contents
	---> 76         self.setupUI()
	     77 
	     78         # %% Window settings

	~/anaconda3/lib/python3.7/site-packages/pandasgui/gui.py in setupUI(self)
	    131 
	    132         # QMainWindow setup
	--> 133         self.make_menu_bar()
	    134         self.setCentralWidget(self.splitter)
	    135 

	~/anaconda3/lib/python3.7/site-packages/pandasgui/gui.py in make_menu_bar(self)
	    190 
	    191         styleMenu = menubar.addMenu('&Set Style')
	--> 192         styleGroup = QtWidgets.QActionGroup(styleMenu, exclusive=True)
	    193 
	    194         # Add an option to the menu for each GUI style that exist for the user's system

	TypeError: 'exclusive' is an unknown keyword argument

**Comment by malapradej** [comment]
I went into the ~/anaconda3/lib/python3.7/site-packages/pandasgui/gui.py file and removed **exclusive=True** and it works.

**Comment by danielseltzer** [comment]
Thanks, @malapradej for noting this. It worked for me as well. For the record, I'm on OSX and brew installed QT5.14, which is the version qmake reports as well.
