### ISSUE TITLE
Allow for drag-drop and CMD opening of pkl files

### ISSUE THREAD

**Issue by rjsdotorg** [adamerose/PandasGUI#156]
In run_with_args.py I modified starting at line 13, and in store.py at line 831.
Works with context menu opening as well.

[pandasgui.zip](https://github.com/adamerose/PandasGUI/files/6792641/pandasgui.zip)

**Comment by adamerose** [comment]
Thanks, I'll include this in the next release. 

For future contributions to open source projects on GitHub you should look into how to submit pull requests (rather than attaching files)
