### ISSUE TITLE
File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/pandasgui/gui.py", line 192, in make_menu_bar     styleGroup = QtWidgets.QActionGroup(styleMenu, exclusive=True) TypeError: 'exclusive' is an unknown keyword argument

### ISSUE THREAD

**Issue by svanschalkwyk** [adamerose/pandasgui#16]
Python 3.7.4

File "/home/steph/anaconda3/envs/bert/lib/python3.7/site-packages/pandasgui/gui.py", line 192, in make_menu_bar
    styleGroup = QtWidgets.QActionGroup(styleMenu, exclusive=True)
TypeError: 'exclusive' is an unknown keyword argument

**Comment by svanschalkwyk** [comment]
Remedy:
In gui.py: 
line 192:
        styleMenu = menubar.addMenu('&Set Style')
#        styleGroup = QtWidgets.QActionGroup(styleMenu,  exclusive=True)
        styleGroup = QtWidgets.QActionGroup(styleMenu) # exclusive is default

**Comment by svanschalkwyk** [comment]
In gui.py, change line 192.

**Comment by dimwael** [comment]
Still not working
