### ISSUE TITLE
Excuse me, how can I embed pandasgui into pyqt5？

### ISSUE THREAD

**Issue by CatNofishing** [adamerose/PandasGUI#169]
This is a great data visualization library, I want to embed it in the pyqt5 program

**Comment by adamerose** [comment]
Whenever you create the GUI like `gui = show(df)`, your `gui` object is a QWidget so you can just embed it like any other PyQt5 widget.

**Comment by CatNofishing** [comment]
Thanks,awesome work!

**Comment by CatNofishing** [comment]
I noticed that the window cannot be reduced to the minimum. I use pandasgui.setMinimumSize(0,0) to lift the window size limit, but it doesn’t work，and any other api to get pandasgui widget and load df replace pandasgui.show(df).
