### ISSUE TITLE
Possible to compile PandasGUI in a .py script?

### ISSUE THREAD

**Issue by devl7b** [adamerose/PandasGUI#175]
I'm working on a script that would benefit from having pandasgui appear to analyze dataframes at key points in the program. Is it possible to compile pandasgui in with my script so that I can make it distributable? 

Love the project, already it has come in extremely handy. Thanks for all your work on this!

**Comment by adamerose** [comment]
A .py script will always be run by Python so "compile PandasGUI in a .py script" seems self contradictory unless I'm misunderstanding, I think you might mean a .exe using something like pyinstaller or py2exe?

If by "distributable" you mean it will work on other machines without a Python installation you could try following this guide: https://www.pythonguis.com/tutorials/packaging-pyqt5-pyside2-applications-windows-pyinstaller/
