### ISSUE TITLE
pandasgui is not installing on Python 3.9

### ISSUE THREAD

**Issue by rodrigomologni** [adamerose/PandasGUI#179]
**The bug**  

I have been able to install the **pandasgui** on Python 3.7 and 3.8, but not on Python 3.9. The error message shows that the Visual Studio C++ 14.0 or greater is required, but it is already installed.

![image](https://user-images.githubusercontent.com/1608652/146817743-f7427403-4951-4fa4-83ce-ac32588e0a2c.png)

**Environment**

OS: Windows 10 x64
Python: 3.9.9
IDE: Sublime Text 4

**Package versions**  

```
ipython==7.30.0
ipython-genutils==0.2.0
pandas==1.3.4
plotly==5.4.0
PyQt5==5.15.6
PyQt5-sip==12.9.0
PyQtWebEngine==5.15.2
```

**Comment by chadkennedyonline** [comment]
One of PandasGUI's dependencies is failing to install. Specifically, wordcloud.

Looking in wordcloud's repo, it looks like this is a known issue: 
https://github.com/amueller/word_cloud/issues/664
https://github.com/amueller/word_cloud/issues/656

Note specifically the solution mentioned here:
https://github.com/amueller/word_cloud/issues/656#issuecomment-985676063

**Comment by rodrigomologni** [comment]
Hi @chadkennedyonline! I installed the **WordCloud** available in [https://www.lfd.uci.edu/~gohlke/pythonlibs](https://www.lfd.uci.edu/~gohlke/pythonlibs/#wordcloud), as suggested by https://github.com/amueller/word_cloud/issues/664#issuecomment-992991559. **PandasGUI** is working now! Thank you for your help!

@acssantos see here.

**Comment by aurao22** [comment]
I do this :

```python
==== Installation of wordcloud package ====

    download wordcloud‑XXX‑cpXX‑cpXXm‑win_amdXXX.whl from http://www.lfd.uci.edu/~gohlke/pythonlibs/#wordcloud
    Copy the file to your current working directory
    Open command prompt from Tools
    python -m pip install wordcloud-1.3.2-cp36-cp36m-win_amd64.whl
````
And it seems to work !
