### ISSUE TITLE
ModuleNotFoundError: No module named 'matplotlib.backends.backend_qt4agg'

### ISSUE THREAD

**Issue by larsihasi** [adamerose/PandasGUI#186]
Could not get demo to work on Apple Macbook M1 (python natively installed using miniconda)

<img width="867" alt="image" src="https://user-images.githubusercontent.com/28692324/149669693-317f7b31-f971-484f-86b8-833cda045475.png">

**Environment**
OS: X Monterey 12.1
Platform: Apple Silicone M1
Python: 3.10.1
IDE: VS Code

<img width="975" alt="image" src="https://user-images.githubusercontent.com/28692324/149669599-843d2ba5-0060-4c49-84c2-b990e7679462.png">

**Package versions**  
TO GET ALL RELEVANT PACKAGE VERSIONS, RUN THIS COMMAND IN BASH AND PASTE THE OUTPUT
pip freeze | grep -i "pyqt\|pandasgui\|plotly\|ipython\|jupyter\|notebook"

<img width="742" alt="image" src="https://user-images.githubusercontent.com/28692324/149669662-6b25db54-28cd-4dbe-9830-7b49d7d81a75.png">
```

**Comment by adamerose** [comment]
Can you try installing with pip instead of conda - MacOS currently isn't supported on PandasGUI conda-forge release

**Comment by larsihasi** [comment]
I think the problem is related to QTWebengine not supported for QT5 on Apple Silicone:
https://successfulsoftware.net/2021/03/05/running-qt-apps-on-m1-arm-macs/
So looking forward when you switch to QT6!
