### ISSUE TITLE
Option for Read Only Presentation?

### ISSUE THREAD

**Issue by herter4171** [adamerose/pandasgui#19]
Hello,

I have a use case in mind that I think `pandasgui` might be a good fit for.  Is there a way to make the grid cells immutable?  I'm looking to pull in tables from a DB, and bad things will inevitably happen if folks can manipulate the data presented in the GUI before copying.

Thanks.

**Comment by adamerose** [comment]
Hi, I did this today and lumped it in with a few other changes I'd been working on. Made a new release and now you can do this:
```
from pandasgui import show
from pandasgui.datasets import pokemon
show(pokemon, settings={'editable':False})
```

Try it out and let me know if there are any issues.
