### ISSUE TITLE
Not sure if this is included or not? The ability to copy the Python code used to create the current view.

### ISSUE THREAD

**Issue by rwebber** [adamerose/PandasGUI#203]
I was looking for a tool that would allow me to use a GUI to buildup my views, but in the end, I need to use python/pandas without the GUI to run the filters/views on an automated schedule. It would be amazing if the pandas code required to create the view from the DF was available to be incorporated into the project.

**Comment by adamerose** [comment]
You can get a history of actions applied to a dataset in PandasGUI as Python code by going to `Edit -> Code History`
