### ISSUE TITLE
Pandasgui 0.2.3 error

### ISSUE THREAD

**Issue by miglto** [adamerose/pandasgui#29]
On Ubuntu 20, python version 3.8.2.

Doing:
pdg.show(data, settings={'block': True})

I am getting the following error:
Traceback (most recent call last):
  File "/home/miguelito/Documents/GitHub/option_pricing/test_pandas.py", line 25, in <module>
    pdg.show(data, settings={'block': True})
  File "/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/gui.py", line 322, in show
    pandas_gui = PandasGui(settings=settings, **kwargs)
TypeError: sip.wrappertype object got multiple values for keyword argument 'settings'

**Comment by adamerose** [comment]
Can you try again with 0.2.3.1

**Comment by miglto** [comment]
Yeap, that works fine. Thank you.

**Comment by miglto** [comment]
However, I am getting these errors in the output:
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-histogram.svg', because: No such file or directory
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-histogram.svg', because: No such file or directory
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-scatter.svg', because: No such file or directory
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-scatter.svg', because: No such file or directory
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-line.svg', because: No such file or directory
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-line.svg', because: No such file or directory
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-bar.svg', because: No such file or directory
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-bar.svg', because: No such file or directory
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-box.svg', because: No such file or directory
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-box.svg', because: No such file or directory
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-violin.svg', because: No such file or directory
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-violin.svg', because: No such file or directory
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-scatter3d.svg', because: No such file or directory
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-scatter3d.svg', because: No such file or directory
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-heatmap.svg', because: No such file or directory
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-heatmap.svg', because: No such file or directory
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-contour.svg', because: No such file or directory
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-contour.svg', because: No such file or directory
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-pie.svg', because: No such file or directory
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-pie.svg', because: No such file or directory
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-splom.svg', because: No such file or directory
qt.svg: Cannot open file '/home/miguelito/.local/lib/python3.8/site-packages/pandasgui/images/plotly/trace-type-splom.svg', because: No such file or directory

**Comment by adamerose** [comment]
Oh I forgot to include the .svg icons in manifest. Fixed with 0.2.3.2

**Comment by miglto** [comment]
Yeap, that fixed it. Thx.
