### ISSUE TITLE
Problem running on Ubuntu via vscode - pandasgui 0.2.3.5

### ISSUE THREAD

**Issue by drbazpython** [adamerose/pandasgui#31]
Hi Adam, when I run pandasgui ..show(titanic).. from my .py file in vscode on Ubuntu, all I get is a black window with 'pandasgui' as title. After a few seconds window closes. No errors reported.
Works Ok from Jupyter Notebook in vscode.
Any suggestions?

**Comment by miglto** [comment]
You could downgrade to a earlier version. I had an issue with 0.2.3.5 and downgraded.

**Comment by adamerose** [comment]
My bad, that was me just pushing a work in progress so I could pull it on another computer and keep working on it, but didn't realize it had an error. I pushed the fix now.

And to be clear, the error wasn't in 0.2.3.5 (which is the latest release on PyPi), it was from the commits to dev afterwards. For version tagged releases I try to test things more thoroughly before pushing.
