### ISSUE TITLE
Cannot import pandasgui

### ISSUE THREAD

**Issue by Lolologist** [adamerose/pandasgui#34]
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

jupyter and jupyterlab both, in python 3.7 pipenv virtual environments, on Ubuntu 18.04.5

**Comment by adamerose** [comment]
Can you try running this snippet to see if your problem is with PyQt5 rather than pandasgui specifically

```
from PyQt5 import QtCore, QtGui, QtWidgets, QtWebEngineWidgets
app = QtWidgets.QApplication([])
```
