### ISSUE TITLE
Type Error if DataFrame contains objects

### ISSUE THREAD

**Issue by adamerose** [adamerose/pandasgui#35]
```
from pandasgui import show
import pandas as pd

df = pd.DataFrame({'a':[1,2,3], 'b':[[1,2,3],[4,5,6],[7,8,9]]})
show(df)
```

Should convert to string and show warning instead of raising exception

**Comment by John-Ted** [comment]
Hi. I added a PR that fixes the issue. The example code above prints a warning and creates the GUI as usual, with the objects changed to their string representations.

**Comment by adamerose** [comment]
@John-Ted Thanks. Pulled and made some changes, looks like the problem is fixed.
