### ISSUE TITLE
Window opens and closes immediately...

### ISSUE THREAD

**Issue by Zombiesen** [adamerose/pandasgui#37]
I tried testing with both of the following code, but both times window opens, appears as 'not responding' and closed down immediately.

I am using Win 10. All dependencies are installed. Double checked. 
CMD does not show any errors.

`import pandas as pd`
`from pandasgui import show`
`path = "https://raw.githubusercontent.com/adamerose/datasets/master/pokemon.csv"`
`pokemon = pd.read_csv(path)`
`gui = show(pokemon)`

and following too..
`import pandas as pd`
`from pandasgui import show`
`df = pd.read_excel('Data.xlsx')`
`gui = show(df)`

There's no problem in excel file, as print(df) shows as expected.

**Comment by Zombiesen** [comment]
I checked Issue #22 
I am running it as script. 

> In a Python script - this should block otherwise the script will continue or finish without giving the user a chance to interact

**Comment by adamerose** [comment]
You mentioned the other issue (where the solution was adding `settings={'block': True}`, but in your two code snippets I don't see that.

To clarify, when you run `show(df)` in a script (as opposed to in IPython or notebooks) the script will continue executing and when it finishes then all windows will immediately close, that's why you need `settings={'block':True}`

So to solve your problem I think you can either run your code snippets in the IPython console, or change them to

```
import pandas as pd
from pandasgui import show
path = "https://raw.githubusercontent.com/adamerose/datasets/master/pokemon.csv"
pokemon = pd.read_csv(path)
gui = show(pokemon , settings={'block': True})
```

```
import pandas as pd
from pandasgui import show
df = pd.read_excel('Data.xlsx')
gui = show(df, settings={'block': True})
```

**Comment by Zombiesen** [comment]
Yes, that worked.. but shouldn't be this the default behavior? 
After reading issue 22, i assumed that's what you did in the code, so that block:true became the default behavior even without explicitly declaring it. 

In any case, this solved it.

**Comment by adamerose** [comment]
> Yes, that worked.. but shouldn't be this the default behavior?

Yeah the issue history is a bit confusing I changed to `block=true` as the default for a while but then changed it back to false, that was my own judgement call. I recommend doing EDA in IPython where blocking isn't necessary to keep the window open and interactive. The benefit of not blocking is that you can open a GUI and look at your data and keep executing commands while it remains open, and can even open multiple GUI windows simultaneously. I think IPython (which includes Jupyter Notebooks) is better and more common than executing full scripts when you're doing the kind of interactive EDA work that would utilize PandasGUI.
