### ISSUE TITLE
Style of pandasgui overwriting style of PyQt5 Gui

### ISSUE THREAD

**Issue by JRoseCPMax** [adamerose/pandasgui#44]
When I open pandasgui from my PyQt5 MainWindow the style of pandasgui overwrites the style of the MainWindow. 
I tried to work around it by using the block setting and apply my old style to the app after I close the pandasgui, but I get "QCoreApplication::exec: The event loop is already running" when I open it blocked. 
Is there another workaround? Can I somehow apply my chosen style to pandasgui while opening the gui?

**Comment by adamerose** [comment]
I stopped the GUI from inheriting existing QApplication instances which should fix this. Install the latest changes with `pip install git+https://github.com/adamerose/pandasgui.git` and let me know if it's not fixed.

**Comment by JRoseCPMax** [comment]
no, did not fix it. It still overwrites my style while opening and i can't block the further execution. 
And now the app doesn't exit properly in vscode. I have to terminate Python over the task manager. 
However when executing the file from the explorer it closes normally on exit. 
(the latest release works just fine)

I think an easy "fix" could be, if i could set the style with the settings option. like:
settings={'style':'windowsvista'}

**Comment by adamerose** [comment]
Okay, made a new commit adding a style option in the settings.

```
from pandasgui.datasets import pokemon
from pandasgui import show

show(pokemon, settings={'style': 'Fusion'})
show(pokemon, settings={'style': 'Windows'})
show(pokemon, settings={'style': 'windowsvista'})
```

Also please check that it exits properly in vscode again, I reverted back to using existing QApplication instance

**Comment by JRoseCPMax** [comment]
yes, everything seems to works as expected, style option works and it exits properly. 
Thank you
