### ISSUE TITLE
ModuleNotFoundError: No module named 'pandasgui'

### ISSUE THREAD

**Issue by halisson-gomides** [adamerose/pandasgui#45]
When trying to install pandasgui, I'm having this problem:

Result from my notebook below:

**!pip install pandasgui:**
`Collecting pandasgui
  Using cached pandasgui-0.2.5.1.tar.gz (83 kB)
Requirement already satisfied: pandas in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from pandasgui) (1.1.3)
Requirement already satisfied: PyQt5 in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from pandasgui) (5.15.1)
Requirement already satisfied: PyQtWebEngine in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from pandasgui) (5.15.1)
Requirement already satisfied: plotly in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from pandasgui) (4.11.0)
Requirement already satisfied: setuptools in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from pandasgui) (41.2.0)
Requirement already satisfied: appdirs in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from pandasgui) (1.4.4)
Requirement already satisfied: dacite in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from pandasgui) (1.5.1)
Requirement already satisfied: pynput in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from pandasgui) (1.7.1)
Requirement already satisfied: IPython in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from pandasgui) (7.18.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from pandas->pandasgui) (2020.1)
Requirement already satisfied: numpy>=1.15.4 in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from pandas->pandasgui) (1.19.2)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from pandas->pandasgui) (2.8.1)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from PyQt5->pandasgui) (12.8.1)
Requirement already satisfied: six in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from plotly->pandasgui) (1.15.0)
Requirement already satisfied: retrying>=1.3.3 in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from plotly->pandasgui) (1.3.3)
Requirement already satisfied: pygments in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from IPython->pandasgui) (2.7.1)
Requirement already satisfied: pickleshare in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from IPython->pandasgui) (0.7.5)
Requirement already satisfied: backcall in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from IPython->pandasgui) (0.2.0)
Requirement already satisfied: decorator in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from IPython->pandasgui) (4.4.2)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from IPython->pandasgui) (3.0.8)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from IPython->pandasgui) (0.4.4)
Requirement already satisfied: jedi>=0.10 in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from IPython->pandasgui) (0.17.2)
Requirement already satisfied: traitlets>=4.2 in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from IPython->pandasgui) (5.0.5)
Requirement already satisfied: wcwidth in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->IPython->pandasgui) (0.2.5)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from jedi>=0.10->IPython->pandasgui) (0.7.1)
Requirement already satisfied: ipython-genutils in c:\users\halissonsg\documents\python scripts\pandasgui\lib\site-packages (from traitlets>=4.2->IPython->pandasgui) (0.2.0)
Using legacy 'setup.py install' for pandasgui, since package 'wheel' is not installed.
Installing collected packages: pandasgui
    Running setup.py install for pandasgui: started
    Running setup.py install for pandasgui: finished with status 'done'
Successfully installed pandasgui-0.2.5.1`

**!pip freeze**:
`appdirs==1.4.4
backcall==0.2.0
colorama==0.4.4
dacite==1.5.1
decorator==4.4.2
ipython==7.18.1
ipython-genutils==0.2.0
jedi==0.17.2
numpy==1.19.2
pandas==1.1.3
pandasgui==0.2.5.1
parso==0.7.1
pickleshare==0.7.5
plotly==4.11.0
prompt-toolkit==3.0.8
Pygments==2.7.1
pynput==1.7.1
PyQt5==5.15.1
PyQt5-sip==12.8.1
PyQtWebEngine==5.15.1
python-dateutil==2.8.1
pytz==2020.1
retrying==1.3.3
six==1.15.0
traitlets==5.0.5
wcwidth==0.2.5`

**import pandas as pd
from pandasgui import show**:
`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-d862d41c98a4> in <module>
      1 import pandas as pd
----> 2 from pandasgui import show

ModuleNotFoundError: No module named 'pandasgui'`

I'm using Windows 10

**Comment by adamerose** [comment]
Hm that's weird. What if you try directly `import pandasgui`? Can you double check your PYTHONPATH and make sure that pip is installing it to the same version of Python that you're using when you try to import it?

**Comment by halisson-gomides** [comment]
I resolved that. Thank you.

I was trying to install it in a virtual environment ... and when creating the environment I skipped an important step ... and it messed up.
When trying to recreate the virtual environment step by step it worked!
