### ISSUE TITLE
Using pandasgui in Colab

### ISSUE THREAD

**Issue by hmok** [adamerose/pandasgui#46]
Hi there,

I wonder if I can run pandasgui in google colab. I tried to use the following for a virtual display but did not work

!pip install pyvirtualdisplay
from pyvirtualdisplay import Display
Display(visible=0, size=(1400, 900)).start()

Any suggestion is greatly appreciated.

Cheers,
Hossein

**Comment by adamerose** [comment]
PandasGUI can be used with Jupyter Notebooks the same way as everywhere else but it will be not be embedded in the browser, it will appear in a separate window. I'm pretty sure it's impossible to embed PyQt widgets in Jupyter Notebooks (which Colab is based on). 
I'm not familiar with `pyvirtualdisplay` and don't understand what your code is trying to do. You just need import `show` from pandasgui and use it as shown in the docs

**Comment by hmok** [comment]
Thank you. Yes you are right. I can easily run it on Jupyter Notebooks but Colab cannot run it. I was hoping there would be a way around it.

**Comment by adamerose** [comment]
So I tried it myself and the error I got was related to `pynput`, which is not totally necessary it just enhances the UX for drag-and-drop export of files... so I can just add a fallback to not use it if the import fails and maybe that will fix it.

**Comment by hmok** [comment]
That would be cool, if it helps. but the main issue is the "failed to acquire X connection" which I believe it has to do with X11 forwarding that may not be possible easily within Colab (or I don't know how to do it in fact!)

**Comment by adamerose** [comment]
@hmok I think it's an error thrown by pynput related to hardware detection

![image](https://user-images.githubusercontent.com/10884874/97078814-d5cdc780-15bc-11eb-8baa-ff6e2ccf2a00.png)

https://stackoverflow.com/questions/53919284/how-to-simulate-python-key-presses-in-google-collab-notebook

**Comment by adamerose** [comment]
Okay so I just tried fixing this, but ran into a 2nd error.
![image](https://user-images.githubusercontent.com/10884874/97079183-dae04600-15bf-11eb-998f-554fcb60c900.png)

After doing more reading about Google Colab it sounds like it's not possible for Qt to work with it at all, so leaving this closed as not possible.
