### ISSUE TITLE
Error with Plotly Express

### ISSUE THREAD

**Issue by shivamy** [adamerose/pandasgui#47]
On trying to run a given example in GH page, getting following error and no plot works. Using 
OS: MacOS 10.15.7
Python: 3.6.4

PandasGUI ERROR — pandasgui.widgets.grapher — Plotly Express cannot process wide-form data with columns of different type.

<img width="1003" alt="pandasgui_error" src="https://user-images.githubusercontent.com/3316983/96799015-017f6080-13b7-11eb-82b0-c151ca27441b.png">

**Comment by adamerose** [comment]
Can you share your Plotly version?

**Comment by shivamy** [comment]
<img width="407" alt="pandasgui_plotly_version" src="https://user-images.githubusercontent.com/3316983/96937991-2b4f8a80-147e-11eb-9522-dcc911090baa.png">

**Comment by shanto268** [comment]
Do you have `plotly-express` installed?

**Comment by adamerose** [comment]
I recognize this error and forget the reason it happens but pretty sure it's related to me creating default empty figures using `px.scatter()`. Changed this, let me know if it didn't fix it
