### ISSUE TITLE
PandasGUI (Not Responding)

### ISSUE THREAD

**Issue by pzyko** [adamerose/pandasgui#48]
Hi,
Trying to use PandasGUI on Windows 10.
Installed via pip in Python 3.8.6
Tried in both Jupyter Notebook and VS Code in .ipynb file.
Added `from pandasgui import show` 

As soon as I use `show(df)` it opens and hangs on the below.

![dwm_mcfci0BLJl](https://user-images.githubusercontent.com/32893752/96835063-c4869d00-148e-11eb-8d34-dfbfae7a9766.png)

**Comment by adamerose** [comment]
Can you try this snippet and see if the window still goes unresponsive?

```
from PyQt5 import QtCore, QtGui, QtWidgets
from IPython import get_ipython

app = QtWidgets.QApplication([])

ipython = get_ipython()
if ipython is not None:
    ipython.magic("gui qt5")

test = QtWidgets.QPushButton("TEST")
test.resize(200,100)
test.show()
```

**Comment by pzyko** [comment]
@adamerose Thanks for getting back to me.
I tried the above in Jupyter Notebook and got the following:

![image](https://user-images.githubusercontent.com/32893752/97122230-816f4700-1778-11eb-9b8d-85443e444b60.png)

Permanently "Not Responding" and can't do anything with it other than close it.

**Comment by alitrack** [comment]
> Can you try this snippet and see if the window goes unresponsive?
> 
> ```python
> from PyQt5 import QtCore, QtGui, QtWidgets
> from IPython import get_ipython
> 
> app = QtWidgets.QApplication([])
> 
> ipython = get_ipython()
> if ipython is not None:
>     ipython.magic("gui qt5")
> 
> test = QtWidgets.QPushButton("TEST")
> test.resize(200,100)
> test.show()
> ```

works 
macOS 10.15.6 (19G2021)
Python 3.7.7

```
from IPython import get_ipython
import pandas as pd
from pandasgui import show

ipython = get_ipython()
if ipython is not None:
    ipython.magic("gui qt5")

titanic = pd.read_csv('/Users/steven/data/titanic3.csv')
show(titanic)
gui = show(titanic)
```
btw, if I want to really stop pandasgui, I have to shutdown the kernel

**Comment by deepcoder** [comment]
I tried the code:

```
from PyQt5 import QtCore, QtGui, QtWidgets
from IPython import get_ipython

app = QtWidgets.QApplication([])

ipython = get_ipython()
if ipython is not None:
    ipython.magic("gui qt5")

test = QtWidgets.QPushButton("TEST")
test.resize(200,100)
test.show()
```
in docker juypter system I described in github issue and received:

```
Kernel Restarting
The kernel for juptyer-notebooks/home automation/Untitled3.ipynb appears to have died. It will restart automatically.

```

**Comment by adamerose** [comment]
> @adamerose Thanks for getting back to me.
> I tried the above in Jupyter Notebook and got the following:
> 
> ![image](https://user-images.githubusercontent.com/32893752/97122230-816f4700-1778-11eb-9b8d-85443e444b60.png)
> 
> Permanently "Not Responding" and can't do anything with it other than close it.

If that snippet goes unresponsive it seems like you have a problem with Jupyter or IPython, rather than specifically PandasGUI. One more thing to try is open IPython directly (without Jupyter) and paste my above snippet, if it still freezes your problem is with IPython, otherwise it's with Jupyter.

And then open an issue in the corresponding project   
https://github.com/jupyter/notebook/issues  
https://github.com/ipython/ipython/issues
