### ISSUE TITLE
supports with dark theme?

### ISSUE THREAD

**Issue by jhk0530** [adamerose/PandasGUI#55]
Hi, thanks for your awesome work. I love it

I didn't use every features of `pandasgui` yet. but i'll try. 
And maybe I expect myself to  write very basic tutorial for my students. 

but there's few suggestion for this project.

1. it's good to see this in colab. 

<img width="1044" alt="스크린샷 2020-10-26 15 33 38" src="https://user-images.githubusercontent.com/6457691/97143461-150b3c80-17a6-11eb-951f-1c603ede5702.png">

2. when pandasgui didn't work in colab. i tried to use it on jupyter lab. (and it worked !)
however as my local pc has dark theme. it didn't work properly.

<img width="698" alt="스크린샷 2020-10-26 15 43 06" src="https://user-images.githubusercontent.com/6457691/97143308-ca89c000-17a5-11eb-90e0-9328e81b84fc.png">

---

Here are my environments
- macOS catalina
- `python` version 3.8.3
- `pandasgui` version 0.2.7
- `pandas` version 1.1.2

thanks again.

**Comment by adamerose** [comment]
Unfortunately I'll never be able to support Colab since it runs on a remote server and cannot run any realtime graphical frameworks like PyQt. 

I'm working on adding a dark theme and will probably publish it in the next 2 weeks.

**Comment by jhk0530** [comment]
wow, thanks!

**Comment by harrisliuwk** [comment]
voting for dark theme +1 !

**Comment by adamerose** [comment]
Just pushed the dark theme (and a matching light theme). Gonna leave this issue open until I'm done working on it since there are still some tweaks needed

![image](https://user-images.githubusercontent.com/10884874/99930241-53046d80-2d1e-11eb-933c-3912f9e6ce36.png)

**Comment by jhk0530** [comment]
awesome!

**Comment by adamerose** [comment]
I wanted to override the titlebar color but turns out that's hard. Putting the solutions I've found below for reference. I only found one PyQt package but it breaks OS features like aero shake and aero snap which isn't a good tradeoff, so keeping the white titlebar for now.

PyQt
https://github.com/gmarull/qtmodern (doesn't support aero snap)
Qt
https://github.com/melak47/BorderlessWindow
https://github.com/Moussa-Ball/BorderlessWindowQt-Modern-Gui
https://github.com/deimos1877/BorderlessWindow
https://github.com/Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle (doesn't support aero snap)

**Comment by jonnojohnson** [comment]
Just tried the theme capability but am getting an issue with the preferences json file not existing.
I did a fresh install of the pandasgui develop branch from github this morning. My environment is Python 3.7 installed via Anaconda:
OS: Win10, Python 3.7.3, IPython 7.19.0, PyQt 5.9.2, PyQt5 5.15, pyqt5-sip 12.8.1, pyqtwebengine 5.15.1
When I from pandasgui import show I get:
~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandasgui\store.py in <module>
     22 preferences_path = os.path.join(LOCAL_DATA_DIR, 'preferences.json')
     23 if not os.path.exists(preferences_path):
---> 24     with open(preferences_path, 'w') as f:
     25         json.dump({'theme': "light"}, f)
     26

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\username\\AppData\\Local\\pandasgui\\preferences.json'

**Comment by adamerose** [comment]
> Just tried the theme capability but am getting an issue with the preferences json file not existing.
> I did a fresh install of the pandasgui develop branch from github this morning. My environment is Python 3.7 installed via Anaconda:
> OS: Win10, Python 3.7.3, IPython 7.19.0, PyQt 5.9.2, PyQt5 5.15, pyqt5-sip 12.8.1, pyqtwebengine 5.15.1
> When I from pandasgui import show I get:
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandasgui\store.py in
> 22 preferences_path = os.path.join(LOCAL_DATA_DIR, 'preferences.json')
> 23 if not os.path.exists(preferences_path):
> ---> 24 with open(preferences_path, 'w') as f:
> 25 json.dump({'theme': "light"}, f)
> 26
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\username\AppData\Local\pandasgui\preferences.json'

Just added a line to create that dir if it doesn't exist, can you check if it works now

**Comment by jonnojohnson** [comment]
That fixed it.

**Comment by geo909** [comment]
Hi,

Thanks a lot for this tool, it's really of great help.

I have tried 0.2.7 (I tried both installing it by pip and installing via git) and I don't seen any option to set the theme. Am I missing something?
