### ISSUE TITLE
qt signal in case the PandasGuiDataFrame.update() is called

### ISSUE THREAD

**Issue by timheb** [adamerose/pandasgui#60]
first of all many thanks for creating the widgets for panda's dataframes. I use the widgets individually in my own GUI.

In my GUI I want to execute certain code once the structure of the filtered dataframe has changed. For this it would be helpful if the PandasGuiDataFrame object emits a qt signal at the end of the update() function.

If you don't like to implement this, it would be good if a small change could be made in the cast() method. Instead of testing the type hard on PandasGuiDataFrame, it would be great if you could use "isinstance". So you could create a derived class of PandasGuiDataFrame.

**Comment by adamerose** [comment]
> In my GUI I want to execute certain code once the structure of the filtered dataframe has changed. For this it would be helpful if the PandasGuiDataFrame object emits a qt signal at the end of the update() function.

The `update` method just goes and resets/refreshes all PyQt objects that rely on store state, and I call this when I edit cells, change filters, or paste data.. so it doesn't necessarily indicate a filter was changed. I think your best option would be just subclass my `PandasGuiDataFrame` and add a signal to any of the methods `add_filter / remove_filter / edit_filter / toggle_filter`.

> If you don't like to implement this, it would be good if a small change could be made in the cast() method. Instead of testing the type hard on PandasGuiDataFrame, it would be great if you could use "isinstance"

Sure, that would be better
