### ISSUE TITLE
Filtering feature doesn't allow multiple word titles

### ISSUE THREAD

**Issue by santiariza15** [adamerose/pandasgui#61]
I get a Syntax Error: invalid syntax error when I try this

**Comment by adamerose** [comment]
This is probably not PandasGUI related, you just need to use proper syntax for your query expression. Multi word column names need to be surrounded by backticks

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.query.html

You can reopen if it actually is a bug, but please post more info like stack trace
