### ISSUE TITLE
Can you add Chinese support?Here is a simple illustration.

### ISSUE THREAD

**Issue by zhige79** [adamerose/pandasgui#64]
I hope you can add Chanese support. This is a good tool.I like it! The simple illustration is in their url.
https://github.com/zhige79/images/blob/main/pandasgui1.png
https://github.com/zhige79/images/blob/main/pandasgui2.png
https://github.com/zhige79/images/blob/main/pandasgui3.png
https://github.com/zhige79/images/blob/main/pandasgui4.png
https://github.com/zhige79/images/blob/main/pandasgui5.png

**Comment by adamerose** [comment]
I'm glad to see this tool getting usage across the world, but I think it's too early in development to start maintaining multiple languages. Any effort to do localization would become outdated after a few releases where I change labels or add new ones. I'd be open to it if there is a way in PyQt5 to globally support Chinese that doesn't require manually maintaining a Chinese translation of each label widget, but it doesn't seem like that's a thing from my reading
