### ISSUE TITLE
Can I keep timezone in index of datetime ?

### ISSUE THREAD

**Issue by GuoqiangJia** [adamerose/PandasGUI#76]
Hi, I have a dataframe with index of datetime type, I found timezone was converted automatically when openning the dataframe by using pandasgui, is there any way to prevent that ? thank you, for example as below.

original index: 2021-01-11 15:20:00+08:00
index showing: 2021-01-11T07:20:00.000000000

**Comment by adamerose** [comment]
PandasGUI just renders columns by converting the values to string, you're seeing it displayed the same way as if you took your date column and applied `.astype(str)`.

> original index: 2021-01-11 15:20:00+08:00

Where do you see it rendered like that? I'd be open to changing this but there are a lot of possible timestamp formats and wondering what made you chose that one.

**Comment by GuoqiangJia** [comment]
Just `print` a dataframe containing `datetime`  column with timezone info, you will see that in console.

**Comment by adamerose** [comment]
It looks correct for me, can you give me the dataset you used?

```
import pandas as pd
df = pd.read_csv(r"https://github.com/adamerose/datasets/raw/master/trump_tweets.csv", parse_dates=['date'])
df['date2'] = df.date.dt.tz_localize('UTC').dt.tz_convert('Asia/Kolkata').astype(str)

from pandasgui import show
show(df)
```


![image](https://user-images.githubusercontent.com/10884874/105439914-b124d280-5c33-11eb-89fa-048d805d2df1.png)

**Comment by GuoqiangJia** [comment]
Sure, see the attachment
[datetime_index.zip](https://github.com/adamerose/PandasGUI/files/5854443/datetime_index.zip)

**Comment by adamerose** [comment]
Huh okay weird... I get the same issue with your pickle but I still can't reproduce it myself, even with `df = df.set_index('date2')` added to my above snippet. Do you know how I can reproduce something like yours programmatically? 

I played with yours and found that the issue appears when you use `df.index.values` which is used in the PandasGUI DataFrame viewer. Usually `.values` matches what you see when you simply print the df but yours somehow doesn't.

![image](https://user-images.githubusercontent.com/10884874/105503617-cf6eea80-5c94-11eb-979a-dcd00ecce3e5.png)

**Comment by adamerose** [comment]
> Sure, see the attachment
> [datetime_index.zip](https://github.com/adamerose/PandasGUI/files/5854443/datetime_index.zip)
> 
> In your case, timezone info would be gone if you set `date2` as `index` .

Thanks, managed to figure out the root cause... you get different results depending whether you use the DataFrame value directly or pull it out of the `.values` array.

```
import pandas as pd
df = pd.read_csv(r"https://github.com/adamerose/datasets/raw/master/trump_tweets.csv", parse_dates=['date'])
print(str(df['date'][0]))
print(str(df['date'].values[0]))
```
```
2009-05-04 13:54:00
2009-05-04T13:54:00.000000000
```
