### ISSUE TITLE
Wordcloud module is missing from requirements

### ISSUE THREAD

**Issue by fdion** [adamerose/PandasGUI#77]
PLEASE FILL OUT THE TEMPLATE

**Describe the bug**  
When using pandasGUI, selecting wordcloud and assigning a column, nothing is rendered. Log shows wordcloud is missing.

**Environment**
OS: (eg. Windows 10)
Python: (eg. 3.8.4)
IDE: (eg. PyCharm)

**Package versions**  
This applies to both PandasGUI-0.2.7 and to develop branch (below)

ipython @ file:///tmp/build/80754af9/ipython_1604101197014/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
-e git+https://github.com/fdion/PandasGUI.git@a31de375dd89e887317fea0069abe9a28115389e#egg=pandasgui
plotly @ file:///tmp/build/80754af9/plotly_1607536586307/work
PyQt5==5.15.2
PyQt5-sip==12.8.1
PyQtWebEngine==5.15.2
```

**Comment by adamerose** [comment]
Thanks, closed your PR since I also added it to setup.py in #2651c82c60cd8bf7f5c329c94946e89b1c80be4a
