### ISSUE TITLE
Mailing list or other communication conduit

### ISSUE THREAD

**Issue by fdion** [adamerose/PandasGUI#86]
Beside doing feature requests or creating bugs, there's a good bit of stuff that would benefit from a mailing list to discuss some development issues, UI/UX feedback from users etc.

**Comment by adamerose** [comment]
I'm open to it, but I've never participated much in mailing lists and not sure what the value added is over GitHub issues. Also, would [discussions ](https://docs.github.com/en/discussions/quickstart) maybe be a better alternative?

I know PyQt has no issue tracker, only a [mailing list,](https://www.riverbankcomputing.com/mailman/listinfo/pyqt) and I found it way harder to find things and read through discussions or bug reports.

**Comment by fdion** [comment]
perhaps github discussions would work, haven't used it. scikit-learn uses a dev mailing list, and they have meetings over some sort of conferencing software (I guess zoom).

**Comment by adamerose** [comment]
I've enabled discussions now. Still leaning towards no mailing list, GitHub has nice UI and is easily viewable for new contributors. I can reconsider later though, you're pretty much the first regular contributor.

> development issues, UI/UX feedback from users

Feel free to open discussion threads on any topics you had in mind, I would love to have input from others on ways to improve the design of this project beyond specific features/fixes.

**Comment by fdion** [comment]
Sounds good. Looks like it has some ways to organize stuff. Even a "show and tell"...

**Comment by fdion** [comment]
And started using it already: https://github.com/adamerose/PandasGUI/discussions/90

**Comment by fdion** [comment]
I think this can be closed @adamerose
