### ISSUE TITLE
Easy selection of variables for filters / filtering in general

### ISSUE THREAD

**Issue by fdion** [adamerose/PandasGUI#88]
## Problem statement
A recurring issue brought up in a test group is that setting up filters is hard. The reason is that, unlike demo data, all their datasets include units in parenthesis, often with unicode. This is very important for the user to know what data they are dealing with (_compounded when metric and imperial units mix in a same dataset_). That means backtick escaping, but it is also really hard and time consuming  to type stuff like:

`Max Operating Temp (°C)`

`Output Capacitance (μF)`

Or things like subscripts or diacritics:
`P₁₁`, `P₁₂`, `énergie cinétique`

This is especially the case when you are live exploring in a meeting and get a question like "how does this perform under such and such conditions" and these are not in the legend.

## Possible solution:
1. drag a drop variables
2. dataframe viewer supporting filtering at column header (like `qgrid` does)

A related issue is that once you have added the variable to the query, **how do you figure out what values are valid / typical**? This is especially problematic for categorical variables. Implementing solution 2 above would fix that. With 1, some form of contextual help would possibly work.

In the past, I've implemented something like 2 for a web based product and customers really liked that functionality.

**Comment by fdion** [comment]
I've started looking at that. Probably will tackle this in a few steps. First, copy / paste. I do need help from someone who's a regular with PyQT: https://github.com/adamerose/PandasGUI/discussions/92

**Comment by adamerose** [comment]
> dataframe viewer supporting filtering at column header (like qgrid does)

That's been in the feature tracker for a while but I haven't started on it, glad to see someone pick it up.

Here's how I imagine it:

1. Right click the column header in the DataFrame viewer. I've already implemented this behavior, but all that's currently in there is `Sort`. You should add a `Filter` option to the menu
2. This pops up a widget in a dialog for entering a filter.
3. When the user submits, the dialog returns a query expression and this gets added to the PandasGuiDataFrameStore with `add_filter`
4. (Optional) Connect these same filter editors

Depending on the data type of the column the widget should look like these:

date -> QDatePicker
int/float -> QSlider spanning min to max
string -> Text box to input regex
boolean, or any data type with less than 20 unique values -> QListWidget with checkboxes that lets users pick specific values

Also need some logic to determine which widget to show for step 4 when editing an existing query expression. Also give an option to switch between them if applicable.

Let me know if you disagree or have questions about any of this

**Comment by adamerose** [comment]
Regarding getting variable names into filters more easily, I think just paste is the best option. Drag and drop would be more work to implement and not really much more functional. I can implement copy/paste of single cells from DataFrame header/index cells, I'll do that tonight won't take long.

**Comment by fdion** [comment]
Between the copy/paste and the PR I just linked, it'll make things easier. Let me know what you think on the autocomplete.

**Comment by adamerose** [comment]
> stuff like:
> Max Operating Temp (°C)
> Output Capacitance (μF)

By the way feel free to add one of those datasets or similar to the `pandasgui.datasets` if it's not private. Data with weird symbols like that would be good for test cases.
