### ISSUE TITLE
Bar plot not working in current develop branch

### ISSUE THREAD

**Issue by fdion** [adamerose/PandasGUI#93]
For the bar plot, `key_cols` is not what you'd think and it is throwing a `KeyError`. Using one of the demo dataset, selecting `Speed` for `x` you get not `Speed` in `key_cols`, but `('S', 'p', 'e', 'e', 'd')`.

_Originally posted by @fdion in https://github.com/adamerose/PandasGUI/discussions/90#discussioncomment-334866_

**Comment by adamerose** [comment]
Just pushed a few commits including a fix for this.

![image](https://user-images.githubusercontent.com/10884874/106969435-d0822c00-6718-11eb-923b-eb1b550dbf79.png)
