### ISSUE TITLE
Is there a way to remove a column from the grapher without resetting it?

### ISSUE THREAD

**Issue by alexn11** [adamerose/PandasGUI#99]
Would be particularly useful when plotting many variables at the same time and to avoid repetitively setting them again.

Sorry in advance if this feature already exists.

**Comment by fdion** [comment]
@alexn11 are you asking about removing a column from, say, `color`, once you've set it to a specific column? If so, double click on the column name, it'll be removed.

**Comment by alexn11** [comment]
Oh thank you, I've missed than! Closing.
